AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SubnetId:
    Type: AWS::EC2::Subnet::Id
Resources:
  Cloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      InstanceType: m5.large
      SubnetId: !Ref SubnetId
      