AWSTemplateFormatVersion: '2010-09-09'

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
            
Outputs:
  DynamoDBTable:
    Description: DynamoDB export
    Value: !GetAtt DynamoDBTable.Arn
    Export:
      Name: DynamoDBTable